### ISSUE TITLE
Webhook alert do not work anymore - api server throws exceptions NoClassDefFoundError and java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by gnobbi** [DependencyTrack/dependency-track#4535]
### Current Behavior

After upgrading Dependency Track from 4.9.x to 4.12.2 The alert with the webhook do not work anymore. The api server shows the following exceptions after uploading an sbom.

> 2025-01-08 10:01:30 java.lang.NoClassDefFoundError: Could not initialize class org.dependencytrack.common.HttpClientPool$Singleton
> 2025-01-08 10:01:30     at org.dependencytrack.common.HttpClientPool.getClient(HttpClientPool.java:67)
> 2025-01-08 10:01:30     at org.dependencytrack.notification.publisher.AbstractWebhookPublisher.publish(AbstractWebhookPublisher.java:85)
> 2025-01-08 10:01:30     at org.dependencytrack.notification.publisher.WebhookPublisher.inform(WebhookPublisher.java:31)
> 2025-01-08 10:01:30     at org.dependencytrack.notification.NotificationRouter.inform(NotificationRouter.java:93)
> 2025-01-08 10:01:30     at alpine.notification.NotificationService.lambda$alertSubscriber$0(NotificationService.java:117)
> 2025-01-08 10:01:30     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 2025-01-08 10:01:30     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 2025-01-08 10:01:30     at java.base/java.lang.Thread.run(Unknown Source)
> 2025-01-08 10:01:30 Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalArgumentException: URI is not absolute [in thread "Alpine-EventService-13"]
> 2025-01-08 10:01:30     at java.base/java.net.URL.of(Unknown Source)
> 2025-01-08 10:01:30     at java.base/java.net.URI.toURL(Unknown Source)
> 2025-01-08 10:01:30     at org.dependencytrack.common.ManagedHttpClientFactory.buildfromEnvironment(ManagedHttpClientFactory.java:306)
> 2025-01-08 10:01:30     at org.dependencytrack.common.ManagedHttpClientFactory.fromEnvironment(ManagedHttpClientFactory.java:263)
> 2025-01-08 10:01:30     at org.dependencytrack.common.ManagedHttpClientFactory.createProxyInfo(ManagedHttpClientFactory.java:228)
> 2025-01-08 10:01:30     at org.dependencytrack.common.ManagedHttpClientFactory.newManagedHttpClient(ManagedHttpClientFactory.java:121)
> 2025-01-08 10:01:30     at org.dependencytrack.common.HttpClientPool$Singleton.<init>(HttpClientPool.java:48)
> 2025-01-08 10:01:30     at org.dependencytrack.common.HttpClientPool$Singleton.<clinit>(HttpClientPool.java:39)
> 2025-01-08 10:01:30     at org.dependencytrack.common.HttpClientPool.getClient(HttpClientPool.java:67)
> 2025-01-08 10:01:30     at org.dependencytrack.tasks.NistMirrorTask.lambda$doDownload$4(NistMirrorTask.java:307)
> 2025-01-08 10:01:30     at io.github.resilience4j.retry.Retry.lambda$decorateCheckedSupplier$1(Retry.java:135)
> 2025-01-08 10:01:30     at io.github.resilience4j.retry.Retry.executeCheckedSupplier(Retry.java:350)
> 2025-01-08 10:01:30     at org.dependencytrack.tasks.NistMirrorTask.doDownload(NistMirrorTask.java:307)
> 2025-01-08 10:01:30     at org.dependencytrack.tasks.NistMirrorTask.getAllFiles(NistMirrorTask.java:220)
> 2025-01-08 10:01:30     at org.dependencytrack.tasks.NistMirrorTask.inform(NistMirrorTask.java:197)
> 2025-01-08 10:01:30     at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:110)
> 2025-01-08 10:01:30     ... 3 common frames omitted
> 2025-01-08 10:01:30 2025-01-08 09:01:30,449 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread

this is a serveral times i think for every webhook request.

### Steps to Reproduce

1. Setup Dependency Track 
2. Create Webhook alert for BomProccessed and NewVulnerabilty
3. Upgrade Dependency Track from 4.9.x to 4.12.2 
4. upload Sbom
5. have a service that consume the webhook alert
6. see the exceptions

### Expected Behavior

Working webhook alert like version 4.9.x

### Dependency-Track Version

4.12.2

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [x] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
It seems the proxy URL you configured via environment variables is not absolute:

> java.lang.IllegalArgumentException: URI is not absolute

Between DT v4.9 and v4.12 we made a jump from Java 17 to Java 21. It's likely that URL validation got more strict between those versions. What format are you using for your proxy URL?

**Comment by gnobbi** [comment]
@nscuro  http://host.docker.internal:5002/api/v1/hook/bom-processed

**Comment by nscuro** [comment]
So this happens when the protocol part of the URL is butchered somehow. Like in this example, where the colon is missing after `http`:

```java
jshell> var foo = URI.create("http//host.docker.internal:5002/api/v1/hook/bom-processed");
foo ==> http//host.docker.internal:5002/api/v1/hook/bom-processed

jshell> foo.toURL()
|  Exception java.lang.IllegalArgumentException: URI is not absolute
|        at URL.of (URL.java:862)
|        at URI.toURL (URI.java:1172)
|        at (#7:1)
```

Or the protocol is missing entirely:

```java
jshell> var foo = URI.create("/host.docker.internal:5002/api/v1/hook/bom-processed");
foo ==> /host.docker.internal:5002/api/v1/hook/bom-processed

jshell> foo.toURL()
|  Exception java.lang.IllegalArgumentException: URI is not absolute
|        at URL.of (URL.java:862)
|        at URI.toURL (URI.java:1172)
|        at (#9:1)
```

How are you setting the proxy URL?

**Comment by gnobbi** [comment]
![Image](https://github.com/user-attachments/assets/3aacfc03-81e1-4085-a137-05d63d426de1)
Im not sure what exactly you mean. I set in the frontend in the frontend

**Comment by gnobbi** [comment]
Ah ok thats a hint. we have a docker compose ymal for two ways one with proxy and one without. It could be that the environmental variable is set with empty value. I will check that.

**Comment by gnobbi** [comment]
Yes that was the problem.Thanks for your great support :)
