### ISSUE TITLE
Project component view displays abnormal "t.$t is not a function"

### ISSUE THREAD

**Issue by fengliu012** [DependencyTrack/dependency-track#3718]
### Current Behavior

After upgrading to 4.11.0 from 4.10.0, I found the component Vulnerabilities bar displayed abnormally when the component  existed vulnerability as below 

![17158483943669](https://github.com/DependencyTrack/dependency-track/assets/134475245/7bab19b4-7b79-4d5b-98cc-ea3c01119515)

Chrome shows the error: "t.$t is not a function"

### Steps to Reproduce

1. component exists vulnerability 

### Expected Behavior

vulnerability bar shows normal

### Dependency-Track Version

4.11.0

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Duplicate of https://github.com/DependencyTrack/frontend/issues/867. Fixed in https://github.com/DependencyTrack/frontend/pull/871.
